[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
command_handler = {path = "../command_handler" }
axum = "0.7.5"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
askama = "0.12.1"
tower-http = {version = "0.5.2", features = ["fs"]}
